/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProtectedIndexRouteImport } from './routes/_protected.index'
import { Route as ProtectedClientsRouteImport } from './routes/_protected.clients'
import { Route as ProtectedPortfolioRouteImport } from './routes/_protected.portfolio'
import { Route as ProtectedProposalsRouteImport } from './routes/_protected.proposals'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedTemplatesRouteImport } from './routes/_protected.templates'
import { Route as ProtectedInvoicesIndexRouteImport } from './routes/_protected.invoices.index'
import { Route as ProtectedInvoicesIdRouteImport } from './routes/_protected.invoices.$id'
import { Route as ProtectedInvoicesNewRouteImport } from './routes/_protected.invoices.new'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClientsRoute = ProtectedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPortfolioRoute = ProtectedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProposalsRoute = ProtectedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTemplatesRoute = ProtectedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInvoicesIndexRoute = ProtectedInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInvoicesIdRoute = ProtectedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInvoicesNewRoute = ProtectedInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof ProtectedClientsRoute
  '/portfolio': typeof ProtectedPortfolioRoute
  '/proposals': typeof ProtectedProposalsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/templates': typeof ProtectedTemplatesRoute
  '/invoices/$id': typeof ProtectedInvoicesIdRoute
  '/invoices/new': typeof ProtectedInvoicesNewRoute
  '/invoices/': typeof ProtectedInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof ProtectedClientsRoute
  '/portfolio': typeof ProtectedPortfolioRoute
  '/proposals': typeof ProtectedProposalsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/templates': typeof ProtectedTemplatesRoute
  '/': typeof ProtectedIndexRoute
  '/invoices/$id': typeof ProtectedInvoicesIdRoute
  '/invoices/new': typeof ProtectedInvoicesNewRoute
  '/invoices': typeof ProtectedInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/clients': typeof ProtectedClientsRoute
  '/_protected/portfolio': typeof ProtectedPortfolioRoute
  '/_protected/proposals': typeof ProtectedProposalsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/templates': typeof ProtectedTemplatesRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/invoices/$id': typeof ProtectedInvoicesIdRoute
  '/_protected/invoices/new': typeof ProtectedInvoicesNewRoute
  '/_protected/invoices/': typeof ProtectedInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/clients'
    | '/portfolio'
    | '/proposals'
    | '/settings'
    | '/templates'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/clients'
    | '/portfolio'
    | '/proposals'
    | '/settings'
    | '/templates'
    | '/'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices'
  id:
    | '__root__'
    | '/_protected'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/_protected/clients'
    | '/_protected/portfolio'
    | '/_protected/proposals'
    | '/_protected/settings'
    | '/_protected/templates'
    | '/_protected/'
    | '/_protected/invoices/$id'
    | '/_protected/invoices/new'
    | '/_protected/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clients': {
      id: '/_protected/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ProtectedClientsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/portfolio': {
      id: '/_protected/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof ProtectedPortfolioRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/proposals': {
      id: '/_protected/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProtectedProposalsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/templates': {
      id: '/_protected/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ProtectedTemplatesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices/': {
      id: '/_protected/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof ProtectedInvoicesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices/$id': {
      id: '/_protected/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof ProtectedInvoicesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/invoices/new': {
      id: '/_protected/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof ProtectedInvoicesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedClientsRoute: typeof ProtectedClientsRoute
  ProtectedPortfolioRoute: typeof ProtectedPortfolioRoute
  ProtectedProposalsRoute: typeof ProtectedProposalsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTemplatesRoute: typeof ProtectedTemplatesRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedInvoicesIdRoute: typeof ProtectedInvoicesIdRoute
  ProtectedInvoicesNewRoute: typeof ProtectedInvoicesNewRoute
  ProtectedInvoicesIndexRoute: typeof ProtectedInvoicesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedClientsRoute: ProtectedClientsRoute,
  ProtectedPortfolioRoute: ProtectedPortfolioRoute,
  ProtectedProposalsRoute: ProtectedProposalsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTemplatesRoute: ProtectedTemplatesRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedInvoicesIdRoute: ProtectedInvoicesIdRoute,
  ProtectedInvoicesNewRoute: ProtectedInvoicesNewRoute,
  ProtectedInvoicesIndexRoute: ProtectedInvoicesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
